config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"
  get '/index', to: 'main#index'

  get '/about', to: 'main#about'

  get '/sales', to: 'main#sales'

  get '/cello1', to: 'main#cello1'
  get '/cello2', to: 'main#cello2'
  get '/cello3', to: 'main#cello3'
  get '/contact', to: 'main#contact' #, as: 'contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @title = "Cello Maker, London, UK"
  end

  def about
    @title = "About"
  end

  def sales
    @title = "Sales"
  end

  def contact
    @title = "Contact"
  #  @contact = Contact.new
  end

  def cello1
    @title = "Gore Booth Copy"
  end

  def cello2
    @title = "Fleming 1717 Copy"
  end

  def cello3
    @title = "Gore Booth Copy"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Return a title on a per-page basis.
  def title
    base_title = "Jeremy Mahrer Cellos"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Me", about_path %></li>
      <li><%= link_to "Stock List", sales_path %></li>
      <li><%= link_to "Contact Me", contact_path %></li>
    </ul>
  </nav>
<!-- 
<h1>Jeremy Mahrer Cellos</h1>  
-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="description" content="This is the website of Jeremy Mahrer Cellos. Jeremy
    Mahrer trained at the London College of Furniture and has been hand crafting cellos for
    over 30 years.">
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <article id="main">
      <%= render 'layouts/header' %>
      <%= yield %>
    </article>
  </body>
</html>

app/views/main/about.html.erb
<section id="page_content">
  <h1>About Jeremy</h1>
  <p>
    Jeremy started playing the cello when he was 9, in 1972. That same year, he gained a
    scholarship to the 
    <%= link_to "Royal College of Music", "http://www.rcm.ac.uk", target: "_blank", rel: "nofollow" %>,
    under the tutelage of 
    <%= link_to "Ivan Andrews", "https://www.youtube.com/watch?v=XVym7gR5qQQ", target: "_blank", rel: "nofollow" %>. By 11, he had achieved Grade 8, by 15 he left most disheartened, not to play cello again for 8 years. And so he attended the 
    <%= link_to "London College of Furniture", "http://www.londonmet.ac.uk/schools/the-cass/", target: "_blank", rel: "nofollow" %>
    for three years. After leaving, he apprenticed with 
    <%= link_to "Malcolm Healey", "http://www.healeyviolins.co.uk/index.php", target: "_blank", rel: "nofollow" %>
    and 
    Michael Shakespeare,
    and since has been working mostly on his own.
  </p>
  <p>
  Jeremy reads an awful lot and swims and is an experienced
  <%= link_to "glider pilot", "https://drive.google.com/file/d/0B3pWHCVCtaBMYW9la3BXQTlQX0E/view?usp=drive_web", target: "_blank", rel: "nofollow" %>.
  </p>
    <p>
    <%= image_tag("CelloWorkshop.jpg", alt: "Creating a Cello") %>
  </p>

</section>

app/views/main/cello1.html.erb
<section id="page_content">
  <h1>Copy of Gore-Booth Stradivarius of 1710</h1>
  <p>
    This cello is based on the Gore-Booth Stradivarius of 1710. The string length is 694mm. The
    back length is 760mm.
  </p>
  <section id="cello_details">
    <%= link_to(image_path("cello1/front.png")) do %>
      <fieldset>
        <%= image_tag("cello1/front_small.png", alt: "Gore-Booth copy") %>
        <caption>Front View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello1/back.png")) do %>
      <fieldset>
        <%= image_tag("cello1/back_small.png", alt: "Gore-Booth copy") %>
        <caption>Back View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello1/scroll_front.png")) do %>
      <fieldset>
        <%= image_tag("cello1/scroll_front_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Front</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello1/scroll_back.png")) do %>
      <fieldset>
        <%= image_tag("cello1/scroll_back_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Back</caption>
      </fieldset>
    <% end %>    
  </section>
</section>

app/views/main/cello2.html.erb
<section id="page_content">
  <h1>Copy of Gore-Booth Stradivarius of 1710</h1>
  <p>
    This cello is also based on the Gore-Booth Stradivarius of 1710. The string length is 690mm. The
    back length is 776mm.  
  </p>
  <section id="cello_details">
    <%= link_to(image_path("cello2/front.png")) do %>
      <fieldset>
        <%= image_tag("cello2/front_small.png", alt: "Gore-Booth copy") %>
        <caption>Front View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello2/back.png")) do %>
      <fieldset>
        <%= image_tag("cello2/back_small.png", alt: "Gore-Booth copy") %>
        <caption>Back View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello2/scroll_front.png")) do %>
      <fieldset>
        <%= image_tag("cello2/scroll_front_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Front</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello2/scroll_back.png")) do %>
      <fieldset>
        <%= image_tag("cello2/scroll_back_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Back</caption>
      </fieldset>
    <% end %>    
  </section>
</section>

app/views/main/cello3.html.erb
<section id="page_content">
  <h1>Copy of Amaryllis Fleming Stradivarius of 1717</h1>
  <p>
    This cello is based on the beautiful Amaryllis Fleming Stradivarius of 1717. This was a composite with back and ribs by Stradivari and the top and head made later by Contreras. On my cello, the string length is 690mm, the back length is 764mm.
  </p>  
  <section id="cello_details">
    <%= link_to(image_path("cello3/front.png")) do %>
      <fieldset>
        <%= image_tag("cello3/front_small.png", alt: "Gore-Booth copy") %>
        <caption>Front View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello3/back.png")) do %>
      <fieldset>
        <%= image_tag("cello3/back_small.png", alt: "Gore-Booth copy") %>
        <caption>Back View</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello3/scroll_front.png")) do %>
      <fieldset>
        <%= image_tag("cello3/scroll_front_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Front</caption>
      </fieldset>
    <% end %>
    <%= link_to(image_path("cello3/scroll_back.png")) do %>
      <fieldset>
        <%= image_tag("cello3/scroll_back_small.png", alt: "Gore-Booth copy") %>
        <caption>Scroll Back</caption>
      </fieldset>
    <% end %>    
  </section>
</section>

app/views/main/contact.html.erb
<section id="page_content">
  <h1>Contacting Jeremy</h1>
  <p>
    If you are interested in finding out more about any of the cellos that are in stock,
    or would like to find out more about my repair and restoration workshop, please
    <a href="mailto:jeremymahrer@gmail.com">
    email me at jeremymahrer@gmail.com</a>, or:
  </p>
  <p>
    send a message to my mobile <%= number_to_phone("07982019185", country_code: "44") %>;
  </p>
  <p>
    or, just write to me at: <br>
    <address>
      68 Walnut Tree Close<br>
      Barnes<br>
      SW13 9QP<br>
    </address>
  </p>

</section>

app/views/main/index.html.erb
<section id="page_content">
  <h1>Jeremy Mahrer Cellos</h1>
  <p>Hello</p>
  <p> 
    I am Jeremy Mahrer, and have been lovingly making hand made cellos for 30 years; while listening to  BBC radio R4 and R3. All the wood I use is hand picked over many days in Germany from
    <%= link_to "Stefan Gleissner", "http://www.gleissner-tonewood.de/English/The_Company/the_company.html", target: "_blank", rel: "nofollow" %>. 
    Many of my cellos are played by professionals around the world. I now have a  
    <%= link_to "small stock", sales_path %>
    of finished cellos for sale. As well as making cellos I also run a repair and restoration workshop.
  </p>

  <p>
    <%= image_tag("JeremyWorkingColour.jpg", alt: "Crafting a Cello") %>
  </p>

</section>

app/views/main/sales.html.erb
<section id="page_content">
  <h1>Current Stock</h1>
  <p>
    I currently have three cellos available, with a fourth in final stages of construction. All three are outstanding in looks and sound, each one being quite distinct. 
  </p>

  <%= link_to(cello1_path, class: "NoDecoration") do %>
    <article class="CelloOverview">
      <h2><q>Gore-Booth Copy</q></h2>
      <p>
        This cello is based on the Gore-Booth Stradivarius of 1710. The string length is 694mm. The
        back length is 760mm.
      </p>
      <%= image_tag("cello1/front_small.png", alt: "Gore-Booth copy") %>
    </article>
  <% end %>

  <%= link_to(cello2_path, class: "NoDecoration") do %>
    <article class="CelloOverview">
      <h2><q>Gore-Booth Copy</q></h2>
      <p>
        This cello is also based on the Gore-Booth Stradivarius of 1710. The string length is 690mm. The
        back length is 776mm.
      </p>
      <%= image_tag("cello2/front_small.png", alt: "Gore-Booth copy") %>
    </article>
  <% end %>

  <%= link_to(cello3_path, class: "NoDecoration") do %>
    <article class="CelloOverview">
      <h2><q>Amaryllis Fleming Copy</q></h2>
      <p>
        This cello is based on the beautiful Amaryllis Fleming Stradivarius of 1717. This was a composite with back and ribs by Stradivari and the top and head made later by Contreras. On my cello, the string length is 690mm, the back length is 764mm.
      </p>
      <%= image_tag("cello3/front_small.png", alt: "Amaryllis Fleming copy") %>
    </article>
  <% end %>
</section>